name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build-images:
    strategy:
      matrix:
        version: ['3.7', '3.8', '3.9', '3.10']
    name: Build Python Docker images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build progress1bar ${{ matrix.version }} image
        run:
          docker image build --build-arg PYTHON_VERSION=${{ matrix.version }} -t progress1bar:${{ matrix.version }} .
      - name: save progress1bar ${{ matrix.version }} image
        if: ${{ matrix.version == '3.9' }}
        run: |
          mkdir -p images
          docker save --output images/progress1bar-${{ matrix.version }}.tar progress1bar:${{ matrix.version }}
      - name: upload progress1bar ${{ matrix.version }} image artifact
        if: ${{ matrix.version == '3.9' }}
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: images/progress1bar-${{ matrix.version }}.tar
  coverage:
    name: Publish Code Coverage Report
    needs: build-images
    runs-on: ubuntu-20.04
    steps:
      - name: download image artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: images/
      - name: load image
        run:
          docker load --input images/progress1bar-3.9.tar
      - name: prepare report
        run: |
          ID=$(docker create progress1bar:3.9)
          docker cp $ID:/code/target/reports/progress1bar_coverage.xml progress1bar_coverage.xml
          sed -i -e 's,filename="progress1bar/,filename="src/main/python/progress1bar/,g' progress1bar_coverage.xml
      - name: upload report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: progress1bar_coverage.xml