name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker image build -t progress1bar:latest .

    - name: Prepare coverage
      run: |
        ID=$(docker create progress1bar)
        docker cp $ID:/code/target/reports/progress1bar_coverage.xml progress1bar_coverage.xml
        sed -i -e 's,filename="progress1bar/,filename="src/main/python/progress1bar/,g' progress1bar_coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: progress1bar_coverage.xml